name: google_map
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.13.1
  firebase_messaging: ^15.2.6

  # Auth
  google_sign_in: ^6.2.1
  flutter_dotenv: ^5.0.2

  # Util
  flutter_localizations:
    sdk: flutter
  talker_flutter: ^4.4.0
  talker_dio_logger: ^4.4.0
  flutter_svg: ^2.0.10+1
  intl: ^0.20.2
  permission_handler: ^12.0.0+1
  url_launcher: ^6.3.0
  flutter_background_service: ^5.0.7
  flutter_local_notifications: ^19.2.1
  flutter_blue_plus: ^1.32.11
  kpostal: ^1.0.0
  kakao_flutter_sdk: ^1.9.5
  kakao_flutter_sdk_navi: ^1.9.5
  crypto: ^3.0.3
  path_provider: ^2.1.4
  device_info_plus: ^11.4.0
  package_info_plus: ^8.0.1
  flutter_native_splash: ^2.4.1
  korea_regexp: ^1.2.1
  image: ^4.2.0
  collection: ^1.18.0

  # StateManagement, DI
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  flutter_hooks: ^0.21.2
  hooks_riverpod: ^2.5.1

  # Network
  dio: ^5.5.0+1
  retrofit: ^4.1.0

  #Storage
  shared_preferences: ^2.3.1
  flutter_secure_storage: ^9.2.2

  # Router
  go_router: ^15.1.3

  # UI
  dropdown_button2: ^2.3.9
  syncfusion_flutter_charts: ^29.2.9
  another_flushbar: ^1.12.30
  flutter_polyline_points: ^2.1.0
  intl_phone_number_input: ^0.7.4
  loader_overlay: ^5.0.0
  loading_animation_widget: ^1.2.1
  camera: ^0.11.0+1
  camera_android_camerax: ^0.6.7+2

  # Location
  geolocator: ^14.0.1
  latlong2: ^0.9.1
  google_maps_flutter: ^2.7.1
  location: ^8.0.1

dependency_overrides:
  meta: ^1.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  retrofit_generator:
  build_runner:
  json_serializable:
  riverpod_generator: ^2.4.1
  riverpod_lint:
  custom_lint:
  freezed: ^3.0.6

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/logo/
    - assets/images/navigation/
    - assets/images/collection/
    - assets/images/collection/

  fonts:
    - family: pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.otf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.otf
          weight: 900
flutter_intl:
  enabled: true

flutter_native_splash:
  color: "#92D050"
  image: assets/images/logo/app_icon.png

  android_12:
    color: "#92D050"
    image: assets/images/logo/app_icon.png